In [10]:
%load_ext nb_black

The nb_black extension is already loaded. To reload it, use:
  %reload_ext nb_black


<IPython.core.display.Javascript object>

# Chapter 2

In [15]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

<IPython.core.display.Javascript object>

In [16]:
output = (
        inputs[0]*weights[0] + 
        inputs[1]*weights[1] + 
        inputs[2]*weights[2] + 
        inputs[3]*weights[3] + 
        bias)
output

4.8

<IPython.core.display.Javascript object>

In [17]:
inputs = [1.0, 2.0, 3.0, 2.5]

weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

outputs = [
    # Neuron 1
    inputs[0]*weights1[0] + 
    inputs[1]*weights1[1] + 
    inputs[2]*weights1[2] +
    inputs[3]*weights1[3] + 
    bias1,

    # Neuron 2
    inputs[0]*weights2[0] + 
    inputs[1]*weights2[1] + 
    inputs[2]*weights2[2] +
    inputs[3]*weights2[3] + 
    bias2,

    # Neuron 3
    inputs[0]*weights3[0] + 
    inputs[1]*weights3[1] + 
    inputs[2]*weights3[2] +
    inputs[3]*weights3[3] + 
    bias3
]
outputs

[4.8, 1.21, 2.385]

<IPython.core.display.Javascript object>

In [18]:
inputs = [1, 2, 3, 2.5]
weights = [
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

<IPython.core.display.Javascript object>

In [20]:
layer_outputs = []

for n_weights, n_bias in zip(weights, biases):
    n_output = 0

    for input, weight in zip(inputs, n_weights):
        n_output += input*weight
    n_output += n_bias

    layer_outputs.append(n_output)

layer_outputs

[4.8, 1.21, 2.385]

<IPython.core.display.Javascript object>

In [2]:
import numpy as np

In [22]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

np.dot(inputs, weights) + bias

4.8

<IPython.core.display.Javascript object>

In [7]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]
biases = [2.0, 3.0, 0.5]

np.dot(weights, inputs) + biases

array([4.8  , 1.21 , 2.385])

To perform a matrix product, the size of the second dimension of the left matrix must match the
size of the first dimension of the right matrix. For example, if the left matrix has a shape of (5,
4) then the right matrix must match this 4 within the first shape value (4, 7). The shape of the
resulting array is always the first dimension of the left array and the second dimension of the right
array, (5, 7).

In [10]:
# 4x7 matrix (4 inputs by 7 batches)
inputs = [
    [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0],
    [2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0],
    [3.0, 6.0, 9.0, 12.0, 15.0, 18.0, 21.0],
    [4.0, 8.0, 12.0, 16.0, 20.0, 24.0, 28.0]
]

# 3x4 matrix (3 neurons by 4 weights)
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]
# 3x0 matrix (3 neurons by nothing), I think if I have [[2], [3], [0.5]] then its 3x1
biases = [2.0, 3.0, 0.5]

# I expect an ouput matrix of 3x7 (3 neurons by 7 batches)
np.dot(weights, inputs)

array([[  4.3 ,   8.6 ,  12.9 ,  17.2 ,  21.5 ,  25.8 ,  30.1 ],
       [ -2.54,  -5.08,  -7.62, -10.16, -12.7 , -15.24, -17.78],
       [  3.19,   6.38,   9.57,  12.76,  15.95,  19.14,  22.33]])

In [14]:
# 3x1 (3 neurons  by 1 bias)
biases = [[2.0], [3.0], [0.5]]

np.dot(weights, inputs) + biases

array([[  6.3 ,  10.6 ,  14.9 ,  19.2 ,  23.5 ,  27.8 ,  32.1 ],
       [  0.46,  -2.08,  -4.62,  -7.16,  -9.7 , -12.24, -14.78],
       [  3.69,   6.88,  10.07,  13.26,  16.45,  19.64,  22.83]])

Testing transpose so I can have my inputs be batches x inputs

In [17]:
inputs = [
    [1.0, 2.0, 3.0, 4.0],
    [2.0, 4.0, 6.0, 8.0],
    [3.0, 6.0, 9.0, 12.0],
    [4.0, 8.0, 12.0, 16.0],
    [5.0, 10.0, 15.0, 20.0],
    [6.0, 12.0, 16.0, 24.0],
    [7.0, 14.0, 21.0, 28.0]
]

arr = np.array(inputs)
np.dot(weights, arr.T)

array([[  4.3 ,   8.6 ,  12.9 ,  17.2 ,  21.5 ,  26.8 ,  30.1 ],
       [ -2.54,  -5.08,  -7.62, -10.16, -12.7 , -15.76, -17.78],
       [  3.19,   6.38,   9.57,  12.76,  15.95,  18.8 ,  22.33]])

In [21]:
biases = [2.0, 3.0, 0.5]
np.dot(weights, arr.T) + np.array([biases]).T

array([[  6.3 ,  10.6 ,  14.9 ,  19.2 ,  23.5 ,  28.8 ,  32.1 ],
       [  0.46,  -2.08,  -4.62,  -7.16,  -9.7 , -12.76, -14.78],
       [  3.69,   6.88,  10.07,  13.26,  16.45,  19.3 ,  22.83]])

nxm = n rows by m columns

In [23]:
# 3x4 matrix (3 batches by 4 inputs)
inputs = [
    [1.0, 2.0, 3.0, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

# 3x4 matrix (3 neurons by 4 weights)
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]
biases = [2.0, 3.0, 0.5]

output = np.dot(inputs, np.array(weights).T)
# 3x3 (3 batches by 3 neurons)
print(output)
print(output + biases)


[[ 2.8   -1.79   1.885]
 [ 6.9   -4.81  -0.3  ]
 [-0.59  -1.949 -0.474]]
[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


matrix + vector = vector is added to each row of the matrix elemenet wise